# Application Settings for different LIVE/STAGING/DEV/TESTING environments goes here!
# This config/app_config.yml file is expected to be hijacked and used by the developers.
# and Symbolic linked in the LIVE SERVER

# To use it locally for testing purposes set local_server to false
environment:
  local_server: true
  enable_caching: true

# Project Management Tool - Assembla API
pm_config:
  tool_name: 'Assembla'
  url: 'https://api.assembla.com'
  version: 'v1'
  response_type: 'json'
  api_key: 'e8f033bf68124b93a4c2' #'d7e21aed516e2b257a7f'
  api_secret_key: '5f7356bf3088b7e759762aa48c391726d1c6e2d8' #'0d058ac99c797210b62a28a7a93c24f25df52136'

# api_key: 'e8f033bf68124b93a4c2'
# api_secret_key: '5f7356bf3088b7e759762aa48c391726d1c6e2d8'